import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <main className="flex h-screen flex-col items-center justify-between p-12">
          <div className="w-full h-screen relative flex">
            <div className="w-full h-full opacity-30">
              <div className="w-full h-full flex justify-center items-center bg-[url('/images/main-background.jpg')] bg-cover bg-center"></div>
            </div>
            <div className="absolute inset-0 flex flex-col items-center justify-center p-5">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
